global using Xunit;
global using AutoMapper;
global using FilmReviewAPI;
global using FilmReviewAPI.DAL;
global using FilmReviewAPI.DTOs;
global using FilmReviewAPI.Models;
global using FilmReviewAPI.Services;
global using Microsoft.EntityFrameworkCore;
global using FilmReviewAPI.Interfaces;