name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3.2.0
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        env:
          TEST_DATABASE_CONNECTION_STRING: 'Server=localhost,1433;Database=filmReviewTestDb;User Id=sa;Password=admin;'
        run: |
          docker pull perlak99/film-review-api:v1.0  # Pull the database image
          docker run -d -p 1433:1433 --name filmreviewtestdb perlak99/film-review-api:v1.0  # Run the database container
          dotnet test --configuration Release --logger "trx;LogFileName=testresults.trx" /p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./TestResults/Coverage/  # Run the tests
          docker stop filmreviewtestdb  # Stop the database container
          docker rm filmreviewtestdb  # Remove the database container
